# Generated by Django 5.0.6 on 2024-05-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='en_persona',
            fields=[
                ('COD_PERSONA', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='EN_PERSONA_PK')),
                ('PRIMER_NOMBRE', models.CharField(max_length=25, verbose_name='PRIMER_NOMBRE')),
                ('SEGUNDO_NOMBRE', models.CharField(max_length=25, verbose_name='SEGUNDO_NOMBRE')),
                ('APELLIDO_PATERNO', models.CharField(max_length=25, verbose_name='APELLIDO_PATERNO')),
                ('APELLIDO_MATERNO', models.CharField(max_length=25, verbose_name='APELLIDO_MATERNO')),
                ('NOMBRES', models.CharField(max_length=200, verbose_name='NOMBRES')),
                ('FECHA_NACIMIENTO', models.DateField(verbose_name='FECHA_NACIMIENTO')),
                ('ESTADO', models.IntegerField(verbose_name='ESTADO')),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200, null=True, verbose_name='OBSERVACIONES')),
                ('SEPARACION_BIENES', models.CharField(blank=True, max_length=1, null=True, verbose_name='SEPARACION_BIENES')),
                ('TIPO_VIVIENDA', models.CharField(blank=True, max_length=3, null=True, verbose_name='TIPO_VIVIENDA')),
                ('NUM_CARGAS', models.IntegerField(blank=True, null=True, verbose_name='NUM_CARGAS')),
                ('NRO_HIJOS', models.IntegerField(blank=True, null=True, verbose_name='NRO_HIJOS')),
                ('NOMBRE_COMERCIAL', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOMBRE_COMERCIAL')),
                ('NOMBRE_ARRENDATARIO_VIVIENDA', models.CharField(blank=True, max_length=80, null=True, verbose_name='NOMBRE_ARRENDATARIO_VIVIENDA')),
                ('TELEFONO_ARRENDATARIO_VIVIENDA', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONO_ARRENDATARIO_VIVIENDA')),
                ('TIPO_LOCAL', models.CharField(blank=True, max_length=3, null=True, verbose_name='TIPO_LOCAL')),
                ('NOMBRE_ARRENDATARIO_LOCAL', models.CharField(blank=True, max_length=80, null=True, verbose_name='NOMBRE_ARRENDATARIO_LOCAL')),
                ('TELEFONO_ARRENDATARIO_LOCAL', models.CharField(blank=True, max_length=80, null=True, verbose_name='TELEFONO_ARRENDATARIO_LOCAL')),
                ('FECHA_ESTABLECIDO_NEGOCIO', models.DateField(blank=True, null=True, verbose_name='FECHA_ESTABLECIDO_NEGOCIO')),
                ('FECHA_INICIO_ACTIVIDAD_ECON', models.DateField(blank=True, null=True, verbose_name='FECHA_INICIO_ACTIVIDAD_ECON')),
                ('CODIGO_REFERENCIA', models.CharField(blank=True, max_length=20, null=True, verbose_name='CODIGO_REFERENCIA')),
                ('CLASE_CONTRIBUYENTE', models.CharField(blank=True, max_length=10, null=True, verbose_name='CLASE_CONTRIBUYENTE')),
                ('OBLIGADO_CONTRIBUYENTE', models.CharField(blank=True, max_length=2, null=True, verbose_name='OBLIGADO_CONTRIBUYENTE')),
                ('ACTIVIDAD_ECONOMICA', models.CharField(blank=True, max_length=2000, null=True, verbose_name='ACTIVIDAD_ECONOMICA')),
                ('TIPO_PERSONA_SRI', models.CharField(blank=True, max_length=8, null=True, verbose_name='TIPO_PERSONA_SRI')),
                ('COD_OCUPACION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_EN_CATALOGO_FK', to='catalogo.en_catalogo', verbose_name='COD_OCUPACION')),
                ('COD_PROFESION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_EN_CATALOGO_FKV1', to='catalogo.en_catalogo', verbose_name='COD_PROFESION')),
                ('ESTADO_CIVIL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_EN_CATALOGO_FKV3', to='catalogo.en_catalogo', verbose_name='ESTADO_CIVIL')),
                ('GENERO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_EN_CATALOGO_FKV4', to='catalogo.en_catalogo', verbose_name='GENERO')),
                ('TIPO_PERSONA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_EN_CATALOGO_FKV2', to='catalogo.en_catalogo', verbose_name='TIPO_PERSONA')),
                ('cod_conyuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EN_PERSONA_CONYUGE_FK', to='P_persona.en_persona', verbose_name='COD_CONYUGE')),
            ],
            options={
                'db_table': 'EN_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUDIT_USUARIO_ING', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING')),
                ('AUDIT_FECHA_ING', models.DateField(null=True, verbose_name='AUDIT_FECHA_ING')),
                ('AUDIT_IP_ING', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING')),
                ('AUDIT_USUARIO_MOD', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD')),
                ('AUDIT_FECHA_MOD', models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD')),
                ('AUDIT_IP_MOD', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD')),
                ('secuencia', models.IntegerField()),
                ('archivo', models.BinaryField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('extension', models.CharField(max_length=200)),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_DIGITALES_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnBienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUDIT_USUARIO_ING', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING')),
                ('AUDIT_FECHA_ING', models.DateField(null=True, verbose_name='AUDIT_FECHA_ING')),
                ('AUDIT_IP_ING', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING')),
                ('AUDIT_USUARIO_MOD', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD')),
                ('AUDIT_FECHA_MOD', models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD')),
                ('AUDIT_IP_MOD', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD')),
                ('secuencia', models.IntegerField()),
                ('tipo_bien', models.CharField(max_length=3)),
                ('avaluo', models.DecimalField(decimal_places=8, max_digits=22)),
                ('hipotecado', models.CharField(default='N', max_length=1)),
                ('institucion_hipoteca', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('observaciones', models.CharField(max_length=200)),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
                ('secuencia_digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.endigitales')),
            ],
            options={
                'db_table': 'EN_BIENES_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('interseccion', models.CharField(blank=True, max_length=80, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('barrio', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_pais', models.CharField(max_length=8)),
                ('cod_lugar', models.CharField(max_length=8)),
                ('principal', models.CharField(blank=True, max_length=1, null=True)),
                ('coordenada_x', models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True)),
                ('coordenada_y', models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True)),
                ('cod_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_DIRECCIONES_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnElectronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('contacto', models.CharField(max_length=800)),
                ('principal', models.CharField(max_length=1)),
                ('cod_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_ELECTRONICOS_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnIdentificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('principal', models.CharField(default='N', max_length=1)),
                ('cod_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_IDENTIFICACIONES_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnTelefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('telefono', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=1)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
                ('cod_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.en_catalogo')),
            ],
            options={
                'db_table': 'EN_TELEFONOS_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUDIT_USUARIO_ING', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING')),
                ('AUDIT_FECHA_ING', models.DateField(null=True, verbose_name='AUDIT_FECHA_ING')),
                ('AUDIT_IP_ING', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING')),
                ('AUDIT_USUARIO_MOD', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD')),
                ('AUDIT_FECHA_MOD', models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD')),
                ('AUDIT_IP_MOD', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD')),
                ('secuencia', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=30, null=True)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('anio', models.IntegerField()),
                ('avaluo', models.DecimalField(decimal_places=8, max_digits=22)),
                ('prendado', models.CharField(default='N', max_length=1)),
                ('institucion_prendado', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('observaciones', models.CharField(max_length=200)),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
                ('secuencia_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='P_persona.endigitales')),
            ],
            options={
                'db_table': 'EN_VEHICULOS_X_PERSONA',
            },
        ),
        migrations.AddConstraint(
            model_name='endigitales',
            constraint=models.UniqueConstraint(fields=('secuencia', 'cod_persona'), name='EN_DIGITALES_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='enbienes',
            constraint=models.UniqueConstraint(fields=('secuencia', 'cod_persona'), name='EN_BIENES_X_PERSONA_PK'),
        ),
        migrations.AlterUniqueTogether(
            name='endireccion',
            unique_together={('secuencia', 'cod_persona')},
        ),
        migrations.AddConstraint(
            model_name='enelectronicos',
            constraint=models.UniqueConstraint(fields=('cod_persona', 'secuencia'), name='EN_ELECTRONICOS_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='enidentificaciones',
            constraint=models.UniqueConstraint(fields=('cod_persona', 'cod_identificacion'), name='EN_IDENTIFICA_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='entelefonos',
            constraint=models.UniqueConstraint(fields=('secuencia', 'cod_persona'), name='EN_TELEFONOS_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='envehiculos',
            constraint=models.UniqueConstraint(fields=('secuencia', 'cod_persona'), name='EN_VEHICULOS_X_PERSONA_PK'),
        ),
    ]
