# Generated by Django 5.0.6 on 2024-05-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_FECHA_ING',
        ),
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_FECHA_MOD',
        ),
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_IP_ING',
        ),
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_IP_MOD',
        ),
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_USUARIO_ING',
        ),
        migrations.RemoveField(
            model_name='en_catalogo',
            name='AUDIT_USUARIO_MOD',
        ),
        migrations.AlterField(
            model_name='en_catalogo',
            name='COD_CATALOGO',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='en_persona',
            name='COD_PERSONA',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EnElectronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('contacto', models.CharField(max_length=800)),
                ('principal', models.CharField(max_length=1)),
                ('cod_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_ELECTRONICOS_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnIdentificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('principal', models.CharField(default='N', max_length=1)),
                ('cod_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_IDENTIFICACIONES_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnTelefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('telefono', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=1)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
                ('cod_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_catalogo')),
            ],
            options={
                'db_table': 'EN_TELEFONOS_X_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='EnDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('interseccion', models.CharField(blank=True, max_length=80, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('barrio', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_pais', models.CharField(max_length=8)),
                ('cod_lugar', models.CharField(max_length=8)),
                ('principal', models.CharField(blank=True, max_length=1, null=True)),
                ('coordenada_x', models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True)),
                ('coordenada_y', models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True)),
                ('cod_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_catalogo')),
                ('cod_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona')),
            ],
            options={
                'db_table': 'EN_DIRECCIONES_X_PERSONA',
                'unique_together': {('secuencia', 'cod_persona')},
            },
        ),
        migrations.AddConstraint(
            model_name='enelectronicos',
            constraint=models.UniqueConstraint(fields=('cod_persona', 'secuencia'), name='EN_ELECTRONICOS_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='enidentificaciones',
            constraint=models.UniqueConstraint(fields=('cod_persona', 'cod_identificacion'), name='EN_IDENTIFICA_X_PERSONA_PK'),
        ),
        migrations.AddConstraint(
            model_name='entelefonos',
            constraint=models.UniqueConstraint(fields=('secuencia', 'cod_persona'), name='EN_TELEFONOS_X_PERSONA_PK'),
        ),
    ]
