# Generated by Django 5.0.6 on 2024-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_persona', '0002_remove_en_catalogo_audit_fecha_ing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_FECHA_ING',
            field=models.DateField(null=True, verbose_name='AUDIT_FECHA_ING'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_FECHA_MOD',
            field=models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_IP_ING',
            field=models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_IP_MOD',
            field=models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_USUARIO_ING',
            field=models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='AUDIT_USUARIO_MOD',
            field=models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD'),
        ),
        migrations.AlterField(
            model_name='en_catalogo',
            name='COD_CATALOGO',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='COD_CATALOGO'),
        ),
        migrations.AlterField(
            model_name='en_persona',
            name='COD_PERSONA',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='EN_PERSONA_PK'),
        ),
    ]
