# Generated by Django 5.0.6 on 2024-05-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='en_catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUDIT_USUARIO_ING', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING')),
                ('AUDIT_FECHA_ING', models.DateField(null=True, verbose_name='AUDIT_FECHA_ING')),
                ('AUDIT_IP_ING', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING')),
                ('AUDIT_USUARIO_MOD', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD')),
                ('AUDIT_FECHA_MOD', models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD')),
                ('AUDIT_IP_MOD', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD')),
                ('cod_catalogo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'EN_CATALOGO',
            },
        ),
        migrations.CreateModel(
            name='EnTipoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUDIT_USUARIO_ING', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_ING')),
                ('AUDIT_FECHA_ING', models.DateField(null=True, verbose_name='AUDIT_FECHA_ING')),
                ('AUDIT_IP_ING', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_ING')),
                ('AUDIT_USUARIO_MOD', models.CharField(max_length=30, null=True, verbose_name='AUDIT_USUARIO_MOD')),
                ('AUDIT_FECHA_MOD', models.DateField(null=True, verbose_name='AUDIT_FECHA_MOD')),
                ('AUDIT_IP_MOD', models.CharField(max_length=20, null=True, verbose_name='AUDIT_IP_MOD')),
                ('cod_tipo_catalogo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'EN_TIPO_CATALOGO',
            },
        ),
        migrations.CreateModel(
            name='EnCatalogoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('cod_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.en_catalogo')),
            ],
            options={
                'db_table': 'EN_CATALOGO_EMPRESA',
            },
        ),
        migrations.AddConstraint(
            model_name='entipocatalogo',
            constraint=models.UniqueConstraint(fields=('cod_tipo_catalogo',), name='EN_TIPO_CATALOGO_PK'),
        ),
        migrations.AddField(
            model_name='encatalogoempresa',
            name='cod_tipo_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.entipocatalogo'),
        ),
        migrations.AddField(
            model_name='en_catalogo',
            name='cod_tipo_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.entipocatalogo'),
        ),
        migrations.AddConstraint(
            model_name='encatalogoempresa',
            constraint=models.UniqueConstraint(fields=('cod_catalogo', 'cod_empresa'), name='EN_CATALOGO_X_EMPRESA_PK'),
        ),
        migrations.AddConstraint(
            model_name='en_catalogo',
            constraint=models.UniqueConstraint(fields=('cod_catalogo',), name='EN_CATALOGO_PK'),
        ),
    ]
