# Generated by Django 5.0.6 on 2024-05-16 20:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cod_usuario', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='COD_USUARIO')),
                ('nombre', models.CharField(max_length=60, verbose_name='NOMBRE')),
                ('pw_app', models.CharField(blank=True, max_length=30, null=True, verbose_name='PW_APP')),
                ('pw_bd', models.CharField(blank=True, max_length=30, null=True, verbose_name='PW_DB')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'AD_USUARIO',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='adUsuarioAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.CharField(max_length=8, verbose_name='COD_EMPRESA')),
                ('cod_agencia', models.CharField(max_length=8, verbose_name='COD_AGENCIA')),
                ('estado', models.IntegerField(blank=True, null=True, verbose_name='ESTADO')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AD_USUARIO_AGENCIA',
            },
        ),
        migrations.CreateModel(
            name='ADUSUARIOEMPRESA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_EMPRESA', models.CharField(max_length=8, verbose_name='COD_EMPRESA')),
                ('estado', models.IntegerField(blank=True, null=True, verbose_name='ESTADO')),
                ('porc_sobregiro_credito', models.IntegerField(verbose_name='PORC_SOBREGIRO_CREDITO')),
                ('autorizacion_egresos_caja', models.CharField(verbose_name='AUTORIZACION_EGRESOS_CAJA')),
                ('apertura_caja_requerido', models.CharField(verbose_name='APERTURA_CAJA_REQUERIDO')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AD_USUARIO_EMPRESA',
            },
        ),
        migrations.AddConstraint(
            model_name='adusuarioagencia',
            constraint=models.UniqueConstraint(fields=('cod_empresa', 'cod_agencia', 'cod_usuario'), name='AD_USUARIO_X_AGENCIA_PK'),
        ),
        migrations.AlterUniqueTogether(
            name='adusuarioagencia',
            unique_together={('cod_agencia', 'cod_empresa'), ('cod_empresa', 'cod_usuario')},
        ),
        migrations.AddConstraint(
            model_name='adusuarioempresa',
            constraint=models.UniqueConstraint(fields=('COD_EMPRESA', 'cod_usuario'), name='AD_USUARIO_X_EMPRESAL_PK'),
        ),
    ]
