# Generated by Django 5.0.6 on 2024-05-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_persona', '0003_en_catalogo_audit_fecha_ing_and_more'),
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adusuario',
            name='cod_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_persona.en_persona', verbose_name='COD_PERSONA'),
        ),
        migrations.AlterField(
            model_name='adusuario',
            name='cod_usuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='COD_USUARIO'),
        ),
        migrations.AlterField(
            model_name='adusuario',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='adusuario',
            name='pw_app',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PW_APP'),
        ),
        migrations.AlterField(
            model_name='adusuario',
            name='pw_bd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PW_DB'),
        ),
    ]
